### ISSUE TITLE
Insecure password hash

### ISSUE THREAD

**Issue by clfs** [cbrnrd/rise#4]
The current repo uses SHA-256 hashes for user's passwords [here](https://github.com/cbrnrd/rise/blob/efd3a221032797b75e548e4dc7df69989ce38241/lib/core/util.rb#L85) and [here](https://github.com/cbrnrd/rise/blob/efd3a221032797b75e548e4dc7df69989ce38241/lib/core/util.rb#L101). This is insecure, since it's easy to determine simple passwords given their SHA-256 hash: repeated guesses will match the hash eventually, or the hash can even be [looked up](https://md5hashing.net/hash/sha256/).

Two ways to eventually improve this could be:
- Use a more secure hashing algorithm like Ruby's bcrypt()
- Enforce minimum length passwords

**Comment by cbrnrd** [comment]
While I agree with the notion that SHA-256 is generally insecure, when I first wrote the program I was using `bcrypt`; however, there were some really yucky dependency issues with windows and osx (with ffi). Since the registration and login signup processes [were just temporarily removed](https://github.com/cbrnrd/rise/pull/5), I'll work on fixing the dependency issues and convert the hashes to bcrypt.
